-- +goose Up
ALTER TABLE posts ADD COLUMN likes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN dislikes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN likes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comments ADD COLUMN dislikes BIGINT NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE posts DROP COLUMN likes;
ALTER TABLE posts DROP COLUMN dislikes;
ALTER TABLE comments DROP COLUMN likes;
ALTER TABLE comments DROP COLUMN dislikes;
